services:
    php:
        container_name: blog.php
        build:
            context: .
            target: frankenphp_dev
        restart: unless-stopped
        environment:
            SERVER_NAME: ":8080"
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            OTEL_PHP_AUTOLOAD_ENABLED: "true"
            OTEL_SERVICE_NAME: "blog"
            OTEL_TRACES_EXPORTER: "otlp"
            OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
            OTEL_PROPAGATORS: "baggage,tracecontext"
        volumes:
            - ./:/app
            - ./.docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./.docker/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
            - caddy_data:/data
            - caddy_config:/config
        ports: [ "8080:8080" ]
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        tty: true

    search:
        container_name: blog.search
        image: getmeili/meilisearch:v1.10
        ports: [ "7700:7700" ]
        volumes:
            - meilisearch_data:/meili_data
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}

    otel-collector:
        container_name: blog.otlp-collector
        image: otel/opentelemetry-collector-contrib:latest
        command: [ "--config", "/etc/otel/config.yaml" ]
        volumes:
            - ./otel-config.yaml:/etc/otel/config.yaml
        ports:
            - "4317:4317"
            - "4318:4318"
        depends_on: [ zipkin ]

    zipkin:
        container_name: blog.zipkin
        image: openzipkin/zipkin:latest
        ports:
            - "9411:9411"

volumes:
    meilisearch_data:
    caddy_data:
    caddy_config:
