services:
    php:
        container_name: blog.php
        build:
            context: .
            target: frankenphp_dev
        restart: unless-stopped
        environment:
            SERVER_NAME: ":8080"
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        volumes:
            - ./:/app
            - ./.docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./.docker/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
            - caddy_data:/data
            - caddy_config:/config
        ports: [ "8080:8080" ]
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        tty: true

    search:
        container_name: blog.search
        image: getmeili/meilisearch:v1.10
        ports: [ "7700:7700" ]
        volumes:
            - meilisearch_data:/meili_data
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}

volumes:
    meilisearch_data:
    caddy_data:
    caddy_config:
