services:
    web:
        container_name: blog.nginx
        image: nginx:latest
        ports: [ "8080:80" ]
        volumes:
            - ".:/var/www/html:ro"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on: [ app ]
        links: [ app ]

    app:
        container_name: blog.app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app
        volumes: [ ".:/var/www/html" ]

    node:
        container_name: blog.node
        image: node:20
        working_dir: /src
        volumes: [ ".:/src" ]
        profiles: [ cli ]

    search:
        container_name: blog.search
        image: getmeili/meilisearch:v1.10
        ports: [ "7700:7700" ]
        volumes:
            - meilisearch_data:/meili_data
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}

volumes:
    meilisearch_data:
