version: '3.4'

services:
  web:
    container_name: blog.web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: app
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
