receivers:
    otlp:
        protocols:
            grpc:
                endpoint: otel-collector:4317
            http:
                endpoint: otel-collector:4318

exporters:
    zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"

service:
    telemetry:
        logs:
            level: info
    pipelines:
        traces:
            receivers: [ otlp ]
            exporters: [ zipkin ]
