@id = 6J0hWoFCuiuWQtjp3K1mXn
@slug = les-structures-de-donnees-en-php

###
# @name Get Articles
GET {{host}}/articles?limit=10
Content-Type: application/json

###
# @name Get Article By ID
GET {{host}}/articles/{{id}}
Content-Type: application/json

###
# @name Get Article By Slug
GET {{host}}/articles/{{slug}}
Content-Type: application/json

###
# @name Get Article Recommendations
GET {{host}}/articles/{{id}}/recommendations
Content-Type: application/json

###
# @name Search Article
GET {{host}}/search/articles?query=PHP
Content-Type: application/json

###
# @name Get Article Comments
GET {{host}}/articles/{{id}}/comments
Content-Type: application/json

###
# @name Post comment
POST {{host}}/comments
Content-Type: application/json

{
    "articleId": {{id}},
    "username": "adrien",
    "message": "coucou"
}

###
# @name Get Projects
GET {{host}}/projects?limit=2
Content-Type: application/json

###
# @name Get Features
GET {{host}}/features
Content-Type: application/json

###
# @name Cache Invalidation by tag
GET {{host}}/cache/invalidation?tag[]=project
Content-Type: application/json
Authorization: Bearer {{token}}
