
###
# @name Publis/Unpublish BlogPage (Contentful)
POST {{host}}/webhook/contentful
Content-Type: application/json
X-Contentful-Topic: ContentManagement.Entry.unpublish
X-Contentful-Webhook-Name: blogpage_publishing
X-Contentful-Webhook-Request-Attempt: 1
X-Contentful-Event-Datetime: 2024-11-05T19:56:11.992Z
X-Contentful-CRN: crn:contentful:::content:spaces/0c7qlubj8id5/environments/master/entries/47oxuTsSSzRFR0KtU4mZS5
X-Contentful-Idempotency-Key: e43ae97e13c5d9563840daf027eee3108eea6b73a51b679b117fdf2ee0da0ff7
x-contentful-signature: 155cd75146e69b1ad46ba1ee175f721bd1aa6a00471b97ce790d588eb4952a88
x-contentful-signed-headers: content-type,x-contentful-crn,x-contentful-event-datetime,x-contentful-idempotency-key,x-contentful-signed-headers,x-contentful-timestamp,x-contentful-topic,x-contentful-webhook-name,x-contentful-webhook-request-attempt
x-contentful-timestamp: 1730836572106

{"sys":{"type":"DeletedEntry","id":"47oxuTsSSzRFR0KtU4mZS5","space":{"sys":{"type":"Link","linkType":"Space","id":"0c7qlubj8id5"}},"environment":{"sys":{"id":"master","type":"Link","linkType":"Environment"}},"revision":7,"createdAt":"2024-11-05T19:56:11.992Z","updatedAt":"2024-11-05T19:56:11.992Z","deletedAt":"2024-11-05T19:56:11.992Z","contentType":{"sys":{"type":"Link","linkType":"ContentType","id":"blogPage"}},"deletedBy":{"sys":{"type":"Link","linkType":"User","id":"6ag7jJYtJBgxYIH4P8YBR3"}}}}

###

