@id = 6J0hWoFCuiuWQtjp3K1mXn
@slug = les-structures-de-donnees-en-php

# @name Get Articles
GET {{host}}/api/articles?limit=2
Content-Type: application/json

###
# @name Get Article By ID
GET {{host}}/api/articles/{{id}}
Content-Type: application/json

###
# @name Get Article By Slug
GET {{host}}/api/articles/{{slug}}
Content-Type: application/json

###
# @name Get Article Recommendations
GET {{host}}/api/articles/{{id}}/recommendations
Content-Type: application/json
