### /admin/cache-invalidation?cacheKey=latest_articles_3
# Invalidate Cache for latest articles query (cacheKey = latest_articles_3)
GET {{host}}/admin/cache-invalidation?cacheKey=latest_articles_3

### /admin/cache-invalidation?cacheKey=articles
# Invalidate Cache for articles list query (cacheKey = articles)
GET {{host}}/admin/cache-invalidation?cacheKey=articles

### /admin/cache-invalidation?cacheKey=article_1
# Invalidate Cache for article with id 1 query (cacheKey = article_1)
GET {{host}}/admin/cache-invalidation?cacheKey=article_1
