name: blog_app
description: "A basic blog app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_html: 3.0.0-beta.2
  dio: ^5.4.0
  url_launcher: ^6.2.3
  flutter_highlighter: ^0.1.1
  flutter_dotenv: ^5.1.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  countly_flutter: ^23.8.0
  logger: ^2.0.2+1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env