name: Publish ghcr.io/adrien-chinour/blog:base-php8.3
on:
    workflow_dispatch:

env:
    IMAGE_NAME: "ghcr.io/adrien-chinour/blog:base-php8.3"

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Log in to the Container registry
                uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and export to Docker
                uses: docker/build-push-action@v6
                with:
                    context: .
                    target: frankenphp_base
                    tags: ${{ env.IMAGE_NAME }}

