name: Run k6 API testsuite
on:
    workflow_dispatch:

jobs:
    run-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup K6
                uses: grafana/setup-k6-action@v1

            -   name: Run local k6 / API Smoke testing
                uses: grafana/run-k6-action@v1
                env:
                    K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
                    K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
                    AUTH_TOKEN: ${{ secrets.ADMIN_AUTH_TOKEN }}
                with:
                    path: k6/api-smoke.js

            -   name: Run local k6 / API Stress testing
                uses: grafana/run-k6-action@v1
                env:
                    K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
                    K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
                    AUTH_TOKEN: ${{ secrets.ADMIN_AUTH_TOKEN }}
                with:
                    path: k6/api-stress.js
