name: 'Performance Testing with Grafana K6'

on: workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Checkout
                uses: actions/checkout@v1

            -   name: "Run k6 smoke testing"
                uses: grafana/k6-action@v0.2.0
                continue-on-error: true
                with:
                    filename: k6/smoke_test.js

            -   name: "Run k6 browser testing"
                uses: grafana/k6-action@v0.2.0
                continue-on-error: true
                with:
                    filename: k6/browser_test.js
