name: "Quality checks"

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
    install:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3

            -   name: "Validate composer.json and composer.lock"
                run: composer validate --strict

            -   name: "Cache Composer packages"
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: "Install Dependencies"
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    ecs:
        runs-on: ubuntu-latest
        needs: [ install ]
        steps:
            -   name: "Coding Style validation with ECS"
                run: vendor/bin/ecs --no-progress-bar

    phpstan:
        runs-on: ubuntu-latest
        needs: [ install ]
        steps:
            -   name: "Static Code validation with PHPStan"
                run: vendor/bin/phpstan analyse --no-progress

    pest:
        runs-on: ubuntu-latest
        needs: [ install ]
        steps:
            -   name: "Run Pest testsuite"
                run: ./vendor/bin/pest --no-progress
