name: "Release on DigitalOcean App Platform"

on:
    workflow_run:
        workflows: [ "Quality checks" ]
        branches: [ main ]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v3
            -   name: "DigitalOcean App Platform deployment"
                # Only deploy when Quality checks is good
                if: ${{ github.event.workflow_run.conclusion == 'success' }}
                uses: digitalocean/app_action@main
                with:
                    app_name: udfn-fr
                    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
